"""Brain Repo — Knowledge Base mirror: export/import KB to markdown."""

import logging
import os
import re
from pathlib import Path

log = logging.getLogger(__name__)


def _slugify(text: str) -> str:
    """Convert text to a URL-safe slug."""
    text = text.lower()
    text = re.sub(r"[^a-z0-9\-_]", "-", text)
    text = re.sub(r"-{2,}", "-", text)
    return text.strip("-") or "connection"


def _get_postgres_connection():
    """Return a psycopg2 connection using environment variables, or None."""
    try:
        import psycopg2  # type: ignore[import]
    except ImportError:
        log.debug("kb_mirror: psycopg2 not available")
        return None

    # Prefer DATABASE_URL (Postgres) if set
    database_url = os.getenv("DATABASE_URL", "")
    if database_url.startswith("postgres"):
        try:
            return psycopg2.connect(database_url)
        except Exception as exc:
            log.warning("kb_mirror: could not connect via DATABASE_URL: %s", exc)
            return None

    # Fall back to individual vars
    host = os.getenv("POSTGRES_HOST", "")
    if not host:
        log.debug("kb_mirror: no POSTGRES_HOST configured, skipping")
        return None

    try:
        return psycopg2.connect(
            host=host,
            port=int(os.getenv("POSTGRES_PORT", "5432")),
            dbname=os.getenv("POSTGRES_DB", ""),
            user=os.getenv("POSTGRES_USER", ""),
            password=os.getenv("POSTGRES_PASSWORD", ""),
        )
    except Exception as exc:
        log.warning("kb_mirror: could not connect to Postgres: %s", exc)
        return None


def export_kb_to_markdown(brain_repo_dir: Path) -> int:
    """Export KB metadata to markdown files in kb-mirror/.

    Exports readable metadata from knowledge_connections and knowledge_chunks.
    Does NOT decrypt content — only exports unencrypted fields.

    Returns count of chunks exported, or 0 if Postgres is not configured.
    """
    conn = _get_postgres_connection()
    if conn is None:
        return 0

    kb_mirror_dir = brain_repo_dir / "kb-mirror"
    connections_dir = kb_mirror_dir / "connections"
    connections_dir.mkdir(parents=True, exist_ok=True)

    exported_chunks = 0
    index_lines = [
        "# Knowledge Base Mirror",
        "",
        "Auto-generated by EvoNexus. Do not edit manually.",
        "",
        "| Connection | Chunks | Source |",
        "|---|---|---|",
    ]

    try:
        cur = conn.cursor()

        # Fetch connections
        cur.execute(
            "SELECT id, name, source, created_at FROM knowledge_connections ORDER BY created_at DESC"
        )
        connections = cur.fetchall()

        for conn_id, conn_name, source, created_at in connections:
            slug = _slugify(str(conn_name))

            # Fetch chunks for this connection (metadata only)
            cur.execute(
                """
                SELECT title, source, created_at
                FROM knowledge_chunks
                WHERE connection_id = %s
                ORDER BY created_at DESC
                """,
                (conn_id,),
            )
            chunks = cur.fetchall()
            chunk_count = len(chunks)
            exported_chunks += chunk_count

            # Write connection markdown
            conn_md_path = connections_dir / f"{slug}.md"
            lines = [
                f"# {conn_name}",
                "",
                f"**Source:** {source or 'N/A'}  ",
                f"**Created:** {created_at}  ",
                f"**Chunks:** {chunk_count}",
                "",
                "## Chunks",
                "",
                "| Title | Source | Created |",
                "|---|---|---|",
            ]
            for title, chunk_source, chunk_created in chunks:
                safe_title = str(title or "").replace("|", "\\|")
                safe_source = str(chunk_source or "").replace("|", "\\|")
                lines.append(f"| {safe_title} | {safe_source} | {chunk_created} |")

            conn_md_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

            index_lines.append(
                f"| [{conn_name}](connections/{slug}.md) | {chunk_count} | {source or ''} |"
            )

        # Write index
        (kb_mirror_dir / "_index.md").write_text("\n".join(index_lines) + "\n", encoding="utf-8")

        cur.close()
        log.info("kb_mirror: exported %d chunks across %d connections", exported_chunks, len(connections))
        return exported_chunks

    except Exception as exc:
        log.error("kb_mirror export failed: %s", exc)
        return 0
    finally:
        try:
            conn.close()
        except Exception:
            pass


def import_markdown_to_kb(markdown_dir: Path, master_key_matches: bool) -> dict:
    """Import KB metadata from markdown mirror files back into the database.

    If master_key_matches=False, imports only metadata and skips encrypted content.

    Returns:
        {"imported": N, "skipped": N, "errors": [str, ...]}
    """
    result = {"imported": 0, "skipped": 0, "errors": []}

    connections_dir = markdown_dir / "connections"
    if not connections_dir.exists():
        log.info("import_markdown_to_kb: no connections dir found at %s", connections_dir)
        return result

    md_files = list(connections_dir.glob("*.md"))
    if not md_files:
        return result

    for md_file in md_files:
        try:
            content = md_file.read_text(encoding="utf-8")
            lines = content.splitlines()

            # Extract connection name from first heading
            conn_name = ""
            for line in lines:
                if line.startswith("# "):
                    conn_name = line[2:].strip()
                    break

            if not conn_name:
                result["skipped"] += 1
                continue

            if not master_key_matches:
                # Only import metadata, skip encrypted content
                log.debug("import_markdown_to_kb: key mismatch, skipping encrypted content for %s", conn_name)
                result["skipped"] += 1
                continue

            # Full import (metadata only — no encrypted fields in mirror)
            result["imported"] += 1
            log.debug("import_markdown_to_kb: imported metadata for %s", conn_name)

        except Exception as exc:
            msg = f"Error importing {md_file.name}: {exc}"
            log.warning(msg)
            result["errors"].append(msg)

    return result
