version: '3.8'

services:
  auth_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    env_file:
      - .env
    volumes:
      - ./pkg:/app/pkg
      - ./main.go:/app/main.go
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum
    networks:
      - local-net

networks:
  local-net:
    external: true