"""
┌──────────────────────────────────────────────────────────────────────────────┐
│ @author: System                                                              │
│ @file: response_models.py                                                    │
│ Specific data response models for Swagger documentation                      │
│ Creation date: December 2025                                                 │
├──────────────────────────────────────────────────────────────────────────────┤
│ @copyright © Evolution API 2025. All rights reserved.                        │
│ Licensed under the Apache License, Version 2.0                               │
└──────────────────────────────────────────────────────────────────────────────┘
"""

from typing import Optional, Dict, Any, List
from pydantic import BaseModel, Field
from uuid import UUID

# Import existing schemas
from src.schemas.schemas import (
    SessionWithMetadata,
    SessionMetadata,
    BulkDeleteSessionsResponse,
    SessionEventResponse
)
from src.schemas.tool_schemas import AvailableTool, ToolCategory
from src.schemas.health import OverallHealth


# ============================================================================
# Client/Usage Schemas
# ============================================================================

class UsageData(BaseModel):
    """Usage data for a client"""
    sessions_this_month: str = Field(..., description="Sessions used this month (format: 'used/limit')")
    active_sessions: str = Field(..., description="Active sessions (format: 'current/limit')")
    memory_retention_days: str = Field(..., description="Memory retention days")
    old_memory_entries: int = Field(..., description="Number of old memory entries")


class UsageSummaryResponse(BaseModel):
    """Usage summary response data"""
    usage: UsageData = Field(..., description="Usage statistics")
    warnings: List[str] = Field(default_factory=list, description="Usage warnings")


class UsageSummaryDictResponse(BaseModel):
    """Usage summary dictionary response"""
    pass  # This will be Dict[str, UsageSummaryResponse] in practice


# ============================================================================
# Chat Schemas
# ============================================================================

class ChatResponseData(BaseModel):
    """Chat response data"""
    response: str = Field(..., description="Response generated by the agent")
    message_history: List[Dict[str, Any]] = Field(default_factory=list, description="Message history")


# ============================================================================
# Session Schemas
# ============================================================================

class SessionListResponse(BaseModel):
    """Session list response data"""
    sessions: List[Dict[str, Any]] = Field(..., description="List of sessions")
    total: int = Field(..., description="Total number of sessions")


class SessionMetricsResponse(BaseModel):
    """Session metrics response data"""
    total_sessions: int = Field(..., description="Total number of sessions")
    active_sessions: int = Field(..., description="Number of active sessions")
    total_messages: int = Field(..., description="Total number of messages")
    # Add more fields as needed based on actual metrics


# ============================================================================
# Integration Schemas
# ============================================================================

class IntegrationConfigResponse(BaseModel):
    """Integration configuration response data"""
    provider: str = Field(..., description="Integration provider name")
    connected: bool = Field(..., description="Whether the integration is connected")
    config: Optional[Dict[str, Any]] = Field(None, description="Additional configuration")


class IntegrationListResponse(BaseModel):
    """List of all integration configurations"""
    configs: Dict[str, IntegrationConfigResponse] = Field(..., description="Integration configurations by provider")
    credentials_configured: Dict[str, bool] = Field(..., description="Whether credentials are configured for each provider")


class OAuthMetadataResponse(BaseModel):
    """OAuth metadata response data"""
    authorization_servers: List[Dict[str, Any]] = Field(..., description="Available authorization servers")
    scopes_supported: List[str] = Field(default_factory=list, description="Supported OAuth scopes")
    response_types_supported: List[str] = Field(default_factory=list, description="Supported response types")
    grant_types_supported: List[str] = Field(default_factory=list, description="Supported grant types")


class OAuthAuthorizationResponse(BaseModel):
    """OAuth authorization URL response"""
    url: str = Field(..., description="OAuth authorization URL")


class OAuthCallbackResponse(BaseModel):
    """OAuth callback response data"""
    username: Optional[str] = Field(None, description="Username from OAuth provider")
    email: Optional[str] = Field(None, description="Email from OAuth provider")


# ============================================================================
# Tools Schemas
# ============================================================================

# ToolResponse uses AvailableTool directly from tool_schemas


class ToolListResponse(BaseModel):
    """Tools list response data"""
    tools: List[Dict[str, Any]] = Field(..., description="List of available tools")
    categories: List[Dict[str, Any]] = Field(default_factory=list, description="Tool categories")
    metadata: Optional[Dict[str, Any]] = Field(None, description="Tools metadata")


# ============================================================================
# A2A Protocol Schemas
# ============================================================================

class A2AAgentCardResponse(BaseModel):
    """A2A agent card response data"""
    name: str = Field(..., description="Agent name")
    description: str = Field(..., description="Agent description")
    url: str = Field(..., description="Agent API URL")
    provider: Dict[str, str] = Field(..., description="Provider information")
    version: str = Field(..., description="Agent version")
    documentationUrl: str = Field(..., description="Documentation URL")
    capabilities: Dict[str, bool] = Field(..., description="Agent capabilities")
    securitySchemes: Dict[str, Any] = Field(..., description="Security schemes")
    security: List[Dict[str, Any]] = Field(..., description="Security requirements")
    defaultInputModes: List[str] = Field(..., description="Default input modes")
    defaultOutputModes: List[str] = Field(..., description="Default output modes")
    skills: List[Dict[str, Any]] = Field(default_factory=list, description="Agent skills")


class A2ASessionListResponse(BaseModel):
    """A2A session list response data"""
    sessions: List[Dict[str, Any]] = Field(..., description="List of sessions")
    total: int = Field(..., description="Total number of sessions")


class A2ASessionHistoryResponse(BaseModel):
    """A2A session history response data"""
    sessionId: str = Field(..., description="Session ID")
    history: List[Dict[str, Any]] = Field(..., description="Conversation history")
    total: int = Field(..., description="Total number of messages")


class A2AJSONRPCResponse(BaseModel):
    """A2A JSON-RPC response data"""
    jsonrpc: str = Field("2.0", description="JSON-RPC version")
    id: Optional[str] = Field(None, description="Request ID")
    result: Optional[Dict[str, Any]] = Field(None, description="Result data")
    error: Optional[Dict[str, Any]] = Field(None, description="Error data")


# ============================================================================
# Discovery Schemas
# ============================================================================

class DiscoverToolsResponse(BaseModel):
    """Discover tools response data"""
    tools: List[Dict[str, Any]] = Field(..., description="List of discovered tools")


# ============================================================================
# Google Calendar Schemas
# ============================================================================

class CalendarItem(BaseModel):
    """Calendar item model"""
    id: str = Field(..., description="Calendar ID")
    name: str = Field(..., description="Calendar name")
    email: Optional[str] = Field(None, description="Calendar email")
    primary: Optional[bool] = Field(False, description="Whether this is the primary calendar")
    selected: Optional[bool] = Field(False, description="Whether this calendar is selected")


class GoogleCalendarCallbackResponse(BaseModel):
    """Google Calendar OAuth callback response"""
    email: Optional[str] = Field(None, description="User email")
    calendars: List[CalendarItem] = Field(default_factory=list, description="List of available calendars")


class CalendarsListResponse(BaseModel):
    """List of calendars response"""
    calendars: List[CalendarItem] = Field(..., description="List of calendars")


class AvailabilitySlot(BaseModel):
    """Availability slot model"""
    start: str = Field(..., description="Slot start time (ISO format)")
    end: str = Field(..., description="Slot end time (ISO format)")


class AvailabilityResponse(BaseModel):
    """Availability check response"""
    available: bool = Field(..., description="Whether the calendar is available")
    slots: List[AvailabilitySlot] = Field(default_factory=list, description="List of available time slots")


class CreateEventResponse(BaseModel):
    """Create event response"""
    success: bool = Field(..., description="Whether the event was created successfully")
    eventId: Optional[str] = Field(None, description="Created event ID")
    meetLink: Optional[str] = Field(None, description="Google Meet link if requested")


class DisconnectResponse(BaseModel):
    """Disconnect response"""
    success: bool = Field(..., description="Whether the disconnection was successful")


# ============================================================================
# Google Sheets Schemas
# ============================================================================

class SpreadsheetItem(BaseModel):
    """Spreadsheet item model"""
    id: str = Field(..., description="Spreadsheet ID")
    name: str = Field(..., description="Spreadsheet name")
    url: Optional[str] = Field(None, description="Spreadsheet URL")
    selected: Optional[bool] = Field(False, description="Whether this spreadsheet is selected")


class GoogleSheetsCallbackResponse(BaseModel):
    """Google Sheets OAuth callback response"""
    email: Optional[str] = Field(None, description="User email")
    spreadsheets: List[SpreadsheetItem] = Field(default_factory=list, description="List of available spreadsheets")


class SpreadsheetsListResponse(BaseModel):
    """List of spreadsheets response"""
    spreadsheets: List[SpreadsheetItem] = Field(..., description="List of spreadsheets")


# Session schemas are imported from src.schemas.schemas
# SessionWithMetadata, SessionMetadata, BulkDeleteSessionsResponse, SessionEventResponse


# ============================================================================
# A2A Health Check Schema
# ============================================================================

class A2AHealthResponse(BaseModel):
    """A2A health check response"""
    status: str = Field(..., description="Health status")

