apiVersion: v1
kind: Service
metadata:
  name: evo-bot-runtime
  labels:
    app: evo-bot-runtime
spec:
  selector:
    app: evo-bot-runtime
  ports:
    - name: http
      port: 80
      targetPort: 8091
  type: ClusterIP
